### ISSUE TITLE
need redirects on legacy.devopsdays.org for `welcome` pages

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-legacy#1]
A very small amount of landing traffic to the older sites is coming in to `events/yyyy-city/welcome`, which is the canonical URL we use for the event homepage. 

On legacy, since it is webby-generated, these won't work. We have to add a redirect for `/events/*/welcome` to `/events/:splat/`

**Comment by mattstratton** [comment]
Fixed in https://github.com/devopsdays/devopsdays-legacy/commit/87e30e0d051d7176afb5aa35c6713dc7ca76ede7

**Comment by bridgetkromhout** [comment]
Does this issue still need to be open?
