### ISSUE TITLE
Charlotte 2015 issues with legacy content

### ISSUE THREAD

**Issue by bridgetkromhout** [devopsdays/devopsdays-legacy#2]
A couple of issues with the legacy content for Charlotte 2015 which would be nice to correct, since Charlotte is happening again in 2017:

* https://legacy.devopsdays.org/events/2015-charlotte/program/ doesn't work so well if you have javascript blocked. Without it blocked you get a link to https://devopsdayscharlotte2015.sched.org and in the console is this message:

_[blocked] The page at https://legacy.devopsdays.org/events/2015-charlotte/program/ was not allowed to run insecure content from http://devopsdayscharlotte2015.sched.org/js/embed.js._

A more seamless fallback for that would be nice so that link would always show. I would also be fine with a redundant link if there isn't a clever way to add a fallback to https://github.com/devopsdays/devopsdays-legacy/blob/master/events/2015-charlotte/program/index.html#L116.

* There is a speaker image on the main page of the site which appears to be a hotlink from elsewhere on the internet - to a non-functional link. The wayback machine says this is the image in question: https://web.archive.org/web/20150908205710/https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAALmAAAAJGEyZjYxOGFkLTgxYWMtNDA4Zi1hMDA2LWU3ZmExM2QwNTJhYw.jpg - is there a recommended way to move that image into our repo for a legacy site? I could just drop it in the top-level directory for the event, since there's not really an appropriate place, but seeking guidance here.

**Comment by mattstratton** [comment]
Fixed mixed-mode issue with c3d3a27d9e5f89e656a46911a045b0fc697b47ab

**Comment by mattstratton** [comment]
@bridgetkromhout I think I would just put that image into the root of `events/2015-charlotte` and then edit the html to point to `events/2015-charlotte/AAEAAQAAAAAAAALmAAAAJGEyZjYxOGFkLTgxYWMtNDA4Zi1hMDA2LWU3ZmExM2QwNTJhYw.jpg` or whatever.

**Comment by mattstratton** [comment]
lol I think that's what you actually did in #6. never mind.
